# Hyprland config file tuned with perfromance and style

####################
### Monitor Conf ###
####################

monitor = eDP-1, 1920x1080@60, 0x0, 1 


#######################
### Set Applications###
#######################

$files = kitty -e yazi
$browser = vivaldi
$menu = wofi show -drun 


################################
### Envionment and Autostart ###
################################

exec-once = waybar &
exec-once = swaylock &
# exec-once = hyprpaper &

env = XCURSOR_SIZE, 20
env = QT_QPA_PLATFORMTHEME, qt5ct


#############
### Input ###
#############

input {
  kb_layout = gb
  follow_mouse = 1
  sensitivity = 0 
}

touchpad {
  natural_scroll = yes
}


#########################
### Gerneal Apperance ###
#########################

general {
  gaps_in = 3
  gaps_out = 7
  border_size = 3
  col.active_border = rgba(7£33ffee) rgba(33aaffee) 45 deg
  col.inactive_border = rgba(444455aa)
  layout = dwindle
}

decoration {
  rounding = 10
  blur {
    enabled = true
    size = 5
    passes = 3
    new_optimizations = true
    ignore_opacity = false
  }
  drop_shadow = yes
  shadow_range = 20
  shadow_render_power = 3
  col.shadow = rgba (00000088)
}

animations {
  enabled = yes
  bezier = easein, 0.3, 0.8, 0.6, 1.0
  animation = windows, 1, 5, easein, popin
  animation = border, 1, 10, default
  animation = fade, 1, 10, default
  animation = workspaces, 1, 6, easein, slide
}























