# configs for hyprland hopefully useful

source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/enviroment.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/applications.conf
source = ~/.config/hypr/appearance.conf
