general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Dim screen at 2.5 minutes
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock at 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Screen off at 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
