general {
    lock_cmd = omarchy-lock-screen                         
    before_sleep_cmd = loginctl lock-session               
    after_sleep_cmd = hyprctl dispatch dpms on             
    ignore_dbus_inhibit = false                            # Allows apps to stop screen-off
}

# 1. Start screensaver at 2.5 minutes
listener {
    timeout = 150                                             
    on-timeout = pidof hyprlock
}

# 2. Lock the session at 5 minutes
listener {
    timeout = 300                      
    on-timeout = loginctl lock-session 
}

# 3. Turn screen off at 5.5 minutes
listener {
    timeout = 330                                            
    on-timeout = hyprctl dispatch dpms off                   
    on-resume = hyprctl dispatch dpms on && brightnessctl -r 
}
