##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0


# --- Window Rules ---
windowrule = float on, match:class ^(impala-float)$
windowrule = size 800 600, match:class ^(impala-float)$
windowrule = center on, match:class ^(impala-float)$


# --- Rules for nmtui floating window ---
windowrule = float on, match:title ^(nmtui)$
windowrule = size 60% 60%, match:title ^(nmtui)$
windowrule = center on, match:title ^(nmtui)$


# --- Rules for Wofi (used by networkmanager-dmenu) ---
windowrule = float on, match:class ^(Wofi)$
windowrule = center on, match:class ^(Wofi)$
