##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*


# --- Wofi ---
windowrule = float on, match:class ^(Wofi)$
windowrule = center on, match:class ^(Wofi)$

# --- Floating TUI (impala-nm, bluetui) ---
windowrule = float on, match:class ^(floating-tui)$
windowrule = size 600 400, match:class ^(floating-tui)$
windowrule = center on, match:class ^(floating-tui)$
